class Connector < ActiveRecord::Base
  belongs_to :page
  
  #Can't use just 'block', because 'block_type' is used by rails
  belongs_to :content_block, :polymorphic => true

  acts_as_list :scope => 'connectors.page_id = #{page_id} and connectors.page_version = #{page_version} and connectors.container = \'#{container}\''
  alias :move_up :move_higher 
  alias :move_down :move_lower 
  
  validates_presence_of :container
  
  named_scope :for_block, lambda {|b| {:conditions => ['connectors.content_block_id = ? and connectors.content_block_type = ?', b.id, b.class.name]}}
  named_scope :for_container, lambda{|container| {:conditions => ['connectors.container = ?', container]} }
  
  #This overrides the method generated by the belongs_to
  #we had to do this because we couldn't figure out how to add the
  #version to the conditions with a polymorphic association
  def content_block
    b = content_block_type.constantize.first(:conditions => {:id => content_block_id, :version => content_block_version})
    
    #If this connector is referring to an older version of the block, we have to look in the versions table
    b ? b : content_block_type.constantize.find(content_block_id).as_of_version(content_block_version)
  end
  
end